name: pop-themes
adopt-info: pop-gtk-theme
base: core20
architectures:
  - all
summary: Pop!_OS GTK and icon themes
description: |
  A snap that exports Pop!_OS GTK and icon themes.

grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Pop
        - $SNAP/share/gtk2/Pop-dark
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Pop
        - $SNAP/share/themes/Pop-dark
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Pop
  sound-themes:
    interface: content
    source:
      read:
        - $SNAP/share/sounds/Pop

parts: 
  pop-gtk-theme:
    after: [utils]
    source: https://github.com/pop-os/gtk-theme.git
    source-commit: 5ab6f1e40aa7067795655cb4d1a1703dc7ce93ca
    source-type: git
    plugin: meson
    meson-parameters: ["--prefix=/", "-Dgnome-shell=false", "-Dgnome-shell-gresource=false"]
    build-packages:
      - sassc
      - libgtk-3-dev
      - libglib2.0-dev
      - libcanberra-gtk-module
      - gnome-common
    override-build: |
      sed -i.bak -e "s|subdir('gnome-shell')||g" meson.build
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/sounds
      - share/gtk2
      - share/themes
    
  pop-icon-theme:
    after: [utils]
    source: https://github.com/pop-os/icon-theme.git
    source-type: git
    plugin: meson
    meson-parameters: ["--prefix=/"]
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Pop
      
  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]

